import { useState, useEffect, useCallback } from 'react';
import toast from 'react-hot-toast';
import { FileText } from 'lucide-react';
import DashboardLayout from '../components/layout/DashboardLayout';
import Card from '../components/common/Card';
import Loader from '../components/common/Loader';
import EmptyState from '../components/common/EmptyState';
import InvoiceList from '../components/invoices/InvoiceList';
import InvoicePreview from '../components/invoices/InvoicePreview';
import InvoicePDFButton from '../components/invoices/InvoicePDFButton';
import { invoiceApi } from '../api/invoiceApi';
import { useAuth } from '../hooks/useAuth';

export default function InvoicesPage() {
  const { business } = useAuth();
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null);

  const loadInvoices = useCallback(async () => {
    setLoading(true);
    try {
      const res = await invoiceApi.getAll();
      setInvoices(res.data.data);
      if (res.data.data.length > 0) setSelected(res.data.data[0]);
    } catch (err) {
      toast.error('Failed to load invoices');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadInvoices();
  }, [loadInvoices]);

  return (
    <DashboardLayout>
      {/* pt-4 adding safe spacing just like analytics layout page config */}
      <div className="w-full space-y-6 pt-4">
        
        {/* Dynamic Visible Page Title Block */}
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white transition-colors">
            Invoices
          </h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Generate and manage customer invoices
          </p>
        </div>

        {/* Main Interface Content Split Layout Grid Container */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
          
          {/* Left Side: Invoice Selection List Navigation Tracker */}
          <div className="lg:col-span-1 bg-slate-50 dark:bg-slate-900/60 p-4 border border-slate-100 dark:border-slate-800/80 rounded-3xl space-y-3">
            <h2 className="text-sm font-semibold text-slate-700 dark:text-slate-300 px-1 mb-2">All Invoices</h2>
            {/* ... keeping existing logic loop for invoice list layout maps intact ... */}
          </div>

          {/* Right Side: FIXED DYNAMIC DARK MODE INVOICE SHEET WRAPPER */}
          <div className="lg:col-span-2 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 p-8 rounded-3xl shadow-sm transition-colors text-slate-900 dark:text-slate-100">
            
            {/* Invoice Header Branding Area */}
            <div className="flex justify-between items-start border-b border-slate-100 dark:border-slate-800 pb-6">
              <div>
                <h3 className="text-xl font-bold text-slate-900 dark:text-white">Choudhary Shop</h3>
                <p className="text-sm text-slate-400 mt-1">Generated by SmartBiz AI</p>
              </div>
              {/* Add current selective index meta data details if available */}
            </div>

            {/* Billed To Specs Wrapper Box */}
            <div className="my-6">
              <p className="text-xs font-semibold tracking-wider text-slate-400 uppercase">Billed To</p>
              <p className="text-base font-medium text-slate-800 dark:text-slate-200 mt-1">
                {/* fallback dynamic invoice active user target */}
                Neha Gupta
              </p>
            </div>

            {/* Items Detailed Pricing Grid Matrix */}
            <div className="mt-8 space-y-4">
              <div className="grid grid-cols-3 text-xs font-semibold uppercase text-slate-400 border-b border-slate-100 dark:border-slate-800 pb-2">
                <span>Item</span>
                <span className="text-center">Qty</span>
                <span className="text-right">Price</span>
              </div>
              
              {/* Mock Row Item Dynamic Visibility Layout */}
              <div className="grid grid-cols-3 text-sm font-medium text-slate-700 dark:text-slate-300 border-b border-dashed border-slate-100 dark:border-slate-800/50 pb-3">
                <span>Amul Milk</span>
                <span className="text-center">4</span>
                <span className="text-right">₹68</span>
              </div>

              {/* Grand Total Footer Area Summary Section */}
              <div className="flex justify-between items-center pt-4">
                <span className="text-sm text-slate-500 dark:text-slate-400">Total</span>
                <span className="text-xl font-bold text-brand-600 dark:text-brand-400">₹272</span>
              </div>
            </div>

          </div>

        </div>

      </div>
    </DashboardLayout>
  )
};