import { formatCurrency } from '../../utils/formatCurrency';
import { formatDate } from '../../utils/formatDate';
import { useAuth } from '../../hooks/useAuth';

export default function InvoicePreview({ invoice }) {
  const { business } = useAuth();

  if (!invoice) return null;

  return (
    <div id="invoice-preview" className="bg-white p-8 rounded-2xl border border-slate-100">
      <div className="flex items-start justify-between mb-8">
        <div>
          <h2 className="text-xl font-bold text-slate-900">{business?.name || 'Your Business'}</h2>
          <p className="text-sm text-slate-500 mt-1">{business?.address || ''}</p>
          <p className="text-sm text-slate-500">{business?.phone || ''}</p>
        </div>
        <div className="text-right">
          <p className="text-lg font-bold text-brand-600">INVOICE</p>
          <p className="text-sm text-slate-500 mt-1">{invoice.invoiceNumber}</p>
          <p className="text-sm text-slate-500">{formatDate(invoice.issuedDate)}</p>
        </div>
      </div>

      <div className="mb-6">
        <p className="text-xs text-slate-400 uppercase tracking-wide mb-1">Billed to</p>
        <p className="text-sm font-medium text-slate-800">{invoice.customerNameSnapshot}</p>
      </div>

      <table className="w-full text-sm mb-6">
        <thead>
          <tr className="border-b border-slate-200">
            <th className="text-left font-medium text-slate-500 py-2">Item</th>
            <th className="text-right font-medium text-slate-500 py-2">Qty</th>
            <th className="text-right font-medium text-slate-500 py-2">Price</th>
            <th className="text-right font-medium text-slate-500 py-2">Subtotal</th>
          </tr>
        </thead>
        <tbody>
          {invoice.items.map((item, i) => (
            <tr key={i} className="border-b border-slate-50">
              <td className="py-2.5 text-slate-700">{item.name}</td>
              <td className="py-2.5 text-right text-slate-600">{item.quantity}</td>
              <td className="py-2.5 text-right text-slate-600">{formatCurrency(item.price)}</td>
              <td className="py-2.5 text-right text-slate-700 font-medium">
                {formatCurrency(item.subtotal)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="flex justify-end">
        <div className="w-56 space-y-2">
          <div className="flex justify-between text-sm text-slate-500">
            <span>Subtotal</span>
            <span>{formatCurrency(invoice.totalAmount)}</span>
          </div>
          {invoice.discount > 0 && (
            <div className="flex justify-between text-sm text-slate-500">
              <span>Discount</span>
              <span>-{formatCurrency(invoice.discount)}</span>
            </div>
          )}
          <div className="flex justify-between text-base font-bold text-slate-900 pt-2 border-t border-slate-200">
            <span>Total</span>
            <span>{formatCurrency(invoice.finalAmount)}</span>
          </div>
        </div>
      </div>

      <p className="text-xs text-slate-400 text-center mt-8">
        Generated by SmartBiz AI · Thank you for your business
      </p>
    </div>
  );
}
